- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_path_shard_build: true
    - ensure-output-dirs

- hosts: all
  pre_tasks:
    - name: Start zuul console daemon
      zuul_console:

  roles:
    - add-build-sshkey
    - prepare-workspace-git
    - validate-host
    - log-inventory
    

