# Start the quickstart tutorial with `docker-compose -p zuul-tutorial
# up` (as directed in the instructions) in order for the network to
# have the expected name so that it can be shared with Jaeger.

# Version 2.1 is required to specify the network name
version: '2.1'

services:
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.58.1
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - "badger:/badger"
    networks:
      - zuul

volumes:
  badger:

networks:
  zuul:
    external: true
    name: zuul-tutorial_zuul
